// Markdown blog renderer.
// - Reads posts.json (generated by .github/workflows/blog-index.yml)
// - List view at /blog/, reader view at /blog/?p=<slug>
// - Supports GFM, fenced code (highlight.js), KaTeX math, Obsidian [[wikilinks]] and ![[image]] embeds

const POSTS_JSON = "posts.json";
const POSTS_DIR = "posts";

const listView = document.getElementById("list-view");
const readerView = document.getElementById("reader-view");
const postList = document.getElementById("post-list");
const postContent = document.getElementById("post-content");
const postCount = document.getElementById("post-count");

function fmtDate(s) {
    if (!s) return "";
    const d = new Date(s);
    if (isNaN(d)) return s;
    return d.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
}

function slugFromQuery() {
    const m = location.search.match(/[?&]p=([^&]+)/);
    return m ? decodeURIComponent(m[1]) : null;
}

function renderList(posts) {
    if (!posts || posts.length === 0) {
        postList.innerHTML = `
            <p style="color: var(--text-dim, #888);">New blog. Coming soon.</p>`;
        if (postCount) postCount.textContent = "0 posts";
        return;
    }
    postCount.textContent = `${posts.length} post${posts.length === 1 ? "" : "s"}`;
    const ul = document.createElement("ul");
    ul.className = "article-list";
    for (const p of posts) {
        const li = document.createElement("li");
        li.className = "article-item";
        li.innerHTML = `
            <div>
                <div class="article-title">
                    <a href="?p=${encodeURIComponent(p.slug)}">${escapeHtml(p.title)}</a>
                </div>
                ${p.excerpt ? `<div class="article-desc">${escapeHtml(p.excerpt)}</div>` : ""}
            </div>
            <span class="article-meta">${fmtDate(p.date)}</span>
        `;
        ul.appendChild(li);
    }
    postList.innerHTML = "";
    postList.appendChild(ul);
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function parseFrontmatter(src) {
    const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
    if (!m) return { data: {}, body: src };
    const data = {};
    for (const line of m[1].split("\n")) {
        const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
        if (!kv) continue;
        let [, k, v] = kv;
        v = v.trim();
        if (v.startsWith("[") && v.endsWith("]")) {
            v = v.slice(1, -1).split(",").map((x) => x.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
        } else if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
            v = v.slice(1, -1);
        }
        data[k] = v;
    }
    return { data, body: src.slice(m[0].length) };
}

function preprocessWikilinks(md, basePath) {
    md = md.replace(/!\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, alt) => {
        const src = target.trim();
        const altText = (alt || src).trim();
        const fullSrc = /^https?:\/\//.test(src) || src.startsWith("/") ? src : `${basePath}/${src}`;
        return `![${altText}](${fullSrc})`;
    });
    md = md.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, display) => {
        const t = target.trim();
        const d = (display || t).trim();
        const slug = t.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
        return `[${d}](?p=${encodeURIComponent(slug)})`;
    });
    return md;
}

async function renderPost(slug, manifest) {
    const meta = (manifest || []).find((p) => p.slug === slug);
    const path = meta ? meta.path : `${POSTS_DIR}/${slug}/index.md`;
    const basePath = path.replace(/\/[^\/]+$/, "");
    let res;
    try {
        res = await fetch(path);
    } catch (e) {
        postContent.innerHTML = `<p>Could not load post: ${escapeHtml(slug)}</p>`;
        return;
    }
    if (!res.ok) {
        postContent.innerHTML = `<p>Post not found: ${escapeHtml(slug)}</p>`;
        return;
    }
    const raw = await res.text();
    const { data, body } = parseFrontmatter(raw);
    const md = preprocessWikilinks(body, basePath);

    if (window.markedHighlight && window.hljs) {
        marked.use(
            markedHighlight.markedHighlight({
                langPrefix: "hljs language-",
                highlight(code, lang) {
                    const language = window.hljs.getLanguage(lang) ? lang : "plaintext";
                    return window.hljs.highlight(code, { language }).value;
                },
            })
        );
    }
    marked.setOptions({ gfm: true, breaks: false });

    const html = marked.parse(md);
    const title = data.title || meta?.title || slug;
    const date = data.date || meta?.date;
    const tags = data.tags || meta?.tags || [];

    postContent.innerHTML = `
        <header class="post-header">
            <h1>${escapeHtml(title)}</h1>
            <div class="post-meta">
                ${date ? `<span>${fmtDate(date)}</span>` : ""}
                ${(Array.isArray(tags) ? tags : []).map((t) => `<span class="chip">${escapeHtml(t)}</span>`).join("")}
            </div>
        </header>
        <div class="post-body">${html}</div>
    `;
    document.title = `${title} - MLAI Blog`;

    if (window.renderMathInElement) {
        renderMathInElement(postContent, {
            delimiters: [
                { left: "$$", right: "$$", display: true },
                { left: "$", right: "$", display: false },
                { left: "\\(", right: "\\)", display: false },
                { left: "\\[", right: "\\]", display: true },
            ],
            throwOnError: false,
        });
    }
}

async function loadManifest() {
    try {
        const res = await fetch(POSTS_JSON, { cache: "no-cache" });
        if (!res.ok) return [];
        const data = await res.json();
        return (data.posts || data || []).sort((a, b) => (b.date || "").localeCompare(a.date || ""));
    } catch {
        return [];
    }
}

async function route() {
    const manifest = await loadManifest();
    const slug = slugFromQuery();
    if (slug) {
        listView.style.display = "none";
        readerView.style.display = "block";
        await renderPost(slug, manifest);
        window.scrollTo(0, 0);
    } else {
        readerView.style.display = "none";
        listView.style.display = "block";
        renderList(manifest);
    }
}

window.addEventListener("popstate", route);
route();
